# S02 Dados e informações usados na classificação de solos

## Encontro—Dúvidas da semana (Paluno, 50 min)

## Leitura—Manual Técnico de Pedologia (37 min)

<!-- Descrição -->

A leitura obrigatória desta semana traz a seção _1.2.2 Principais determinações e métodos de análises utilizados em levantamentos de solos no Brasil_ do [Manual Técnico de Pedologia](https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf) (IBGE, 2015, p. 151-169). Ela tem como objetivo fazer com que você se familiarize com essas determinações e métodos de análise. Conhecê-las é de fundamental importância, pois a classificação de solos requer a caracterização completa do solo. E isso só pode ser feito enviando amostras para laboratórios de análise qualificados.

À primeira vista, o tema pode lhe parecer complexo, sobretudo porque você ainda não deve ter cursado nenhuma disciplina que tratasse especificamente dos métodos de análise química e física do solo. Contudo, como foi dito acima, o objetivo é que você apenas se familiarize com as principais determinações e métodos de análise. Sem isso, você terá bastante dificuldade para utilizar o Sistema Brasileiro de Classificação de Solos.

Boa leitura e até breve!

## Questionário—Dados para classificação de solos (10 min)

<!-- Descrição -->

Este questionário também faz parte da primeira avaliação individual da nossa disciplina. Aqui, o objetivo é aferir seu conhecimento sobre os dados morfológicos, químicos e físicos utilizados para a classificação de solos. Assim como no questionário anterior, são 10 questões a serem respondidas em até 10 minutos. Você continua dispondo de três tentativas para responder ao questionário, sendo sua nota dada pela média aritmética de todas as tentativas.

Você não precisa se preocupar com o fato de ainda não cursado disciplinas que tratassem especificamente de métodos de análise química e física do solo. A leitura atenta da seção _1.2.2 Principais Determinações e Métodos de Análises Utilizados em Levantamentos de Solos no Brasil_ do [Manual Técnico de Pedologia](https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf) (IBGE, 2015, p. 151-169) é suficiente para você ter sucesso na resolução do questionário.

Bom trabalho e até breve!

## Fórum I—Fontes de dados e informações do solo (20 min)

<!-- Duração: de 3 semanas -->

<!-- Descrição -->

Você já deve saber que o seu papel como engenheiro(a) será o de resolver problemas agronômicos de interesse da sociedade. A forma mais eficiente de fazer isso é aplicando os princípios do método científico. Independente do problema que você terá que resolver, um dos primeiros passos vai sempre consistir em compilar os dados e informações existentes sobre o problema à mão. Depois de analisar esses dados e informações, você terá condições de decidir se necessita coletar mais dados ou se já consegue formular uma resposta satisfatória o problema.

Neste primeiro fórum, que tem duração de três semana, o objetivo é responder a duas questões fundamentais. Primeiro, quais são as estratégias mais eficientes para encontrar fontes de dados e informações de recursos do solo e da terra de uma determinada região geográfica? Segundo, quais são as características que permitem identificar que uma dessas fontes é confiável?

Lembre-se de que você precisa interagir com seus colegas, pelo menos, uma vez por semana para completar essa atividade.

Bom trabalho e até breve!

## Encontro—Organização de informações de recursos do solo e da terra (50 min)

<!-- Descrição -->

O objetivo dessa disciplina é que você chegue ao final dela sendo capaz de organizar informações sobre os recursos do solo e da terra de regiões geográficas. Em outras palavas, que você seja capaz de encontrar fontes confiáveis de dados e informação, sumariar as informações encontradas, reportar as relações existentes entre os componentes do meio físico, e produzir conteúdo digital para comunicação. O projeto de extensão Wikipedon foi criado exatamente para te ajudar a desenvolver essa capacidade.

Em nosso segundo encontro, vamos conversar sobre como organizar informações de recursos do solo e da terra para publicação na Wikipédia. Vamos abordar tópicos como as páginas de teste e o editor de texto da Wikipédia. Veremos também como o WMF Outreach Dashboard nos auxiliará na organização do trabalho em grupo. Enquanto nosso encontro não chega, você pode ir se familiarizando com a [edição de projetos wiki](https://pt.wikiversity.org/wiki/Ajuda:Como_editar_em_um_projeto_Wiki) e conhecer mais sobre o uso da [Wikipédia na educação](https://pt.wikiversity.org/wiki/Oficinas_Wikimedia_%26_Educa%C3%A7%C3%A3o).

## Wikipedon—Formação dos grupos de trabalho (10 min)
<!-- URL externa -->
https://outreachdashboard.wmflabs.org/courses/Universidade_Tecnol%C3%B3gica_Federal_do_Paran%C3%A1/Wikipedon_2020-02_(2020)

Essa é a primeira etapa do [trabalho em grupo](https://pt.wikiversity.org/wiki/Wikipedon) e algumas tarefas importante precisam ser cumpridas. A primeira delas consiste exatamente em constituir seu grupo de trabalho. Para isso, você precisa identificar dois colegas com os quais gostaria de trabalhar durante todo o semestre letivo. Em seguida, você e seus colegas de trabalho devem escolher um dos quinze [municípios paranaenses](https://outreachdashboard.wmflabs.org/courses/Universidade_Tecnol%C3%B3gica_Federal_do_Paran%C3%A1/Wikipedon_2020-02_(2020)/articles/available) participantes do projeto Wikipedon. Esse é o município para o qual seu grupo terá que produzir conteúdo digital sobre os recursos do solo e da terra para publicação na Wikipédia.

Depois de formado o grupo de trabalho e selecionado o município de interesse, você precisa se inscrever no [WMF Outreach Dashboard](https://outreachdashboard.wmflabs.org/courses/Universidade_Tecnológica_Federal_do_Paraná/Wikipedon_2020-02_(2020)?locale=pt-br&enroll=nitossolo?locale=pt-br). O WMF Outreach Dashboard é a plataforma que nós utilizaremos para gerir o trabalho em grupo (você precisa ter uma [conta de usuário da Wikipédia](https://pt.wikipedia.org/w/index.php?title=Especial:Criar_conta) para se inscrever). Completada a inscrição, você só precisa registrar no WMF Outreach Dashboard o município com o qual vai trabalhar. Fique tranquilo pois nós preparamos um [tutorial](https://pt.wikiversity.org/wiki/Wikipedon) para lhe auxiliar nessa tarefa.

Bom trabalho e até breve!
