# S03 Fontes de dados e informações do solo

Nesta semana, você conhecerá algumas das mais importantes fontes de dados de recursos do solo do Brasil e do mundo. Você vai conhecer as características desejáveis de uma base pública de dados do solo, bem como maneiras alternativas de produção de dados do solo. Também lhe serão apresentadas as três leis e os oito princípios dos dados abertos, e como cada repositório de dados do solo atende a essas leis e princípios. Ao final da semana, espera-se que você seja capaz de selecionar fontes confiáveis de dados de recursos do solo de regiões geográficas do território brasileiro.

Para alcançar esse objetivo, você deve fazer a leitura de dois artigos publicados no [Boletim Informativo](https://www.sbcs.org.br/?post_type=boletim) da Sociedade Brasileira de Ciência do Solo ([SBCS](https://www.sbcs.org.br)). Esses artigos servirão de base para você responder ao questionário da semana, momento em que você poderá verificar seu aprendizado. Eles também proverão elementos para sua segunda participação no fórum sobre fontes de dados e informações do solo. Finalmente, você e seus colegas de trabalho encontrarão pistas importantes sobre onde buscar dados dos recursos do solo e da terra do município com o qual estão trabalhando no projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon).

## Encontro—Dúvidas da semana (Paluno, 50 min)

## Leitura—Boletim Informativo da SBCS (7 min + 15 min)
<!-- Descrição -->
* SAMUEL-ROSA, A.; VASQUES, G. M. Dados para aplicações pedométricas em larga escala no Brasil. Boletim Informativo da SBCS, v. 43, n. 3, p. 22–24, 2017. Disponível em: <https://www.sbcs.org.br/wp-content/uploads/2018/01/boletimsbcs32017ebook_03_01_2018_10_45_30_id_36404.pdf>
* SAMUEL-ROSA, A. Vamos abrir os dados da pesquisa sobre o solo? Boletim Informativo da SBCS, v. 45, n. 1, p. 27–31, 2019. Disponível em: <https://www.sbcs.org.br/wp-content/uploads/2019/06/Boletim-SBCS-Volume-45-N%C3%BAmero-1.pdf>

## Questionário—Fontes de dados e informações do solo (10 min)

## Fórum I—Fontes de dados e informações do solo (10 min)
<!-- Descrição -->
Quais são as estratégias mais eficientes para encontrar fontes de dados e informações de recursos do solo e da terra de uma determinada região geográfica? Quais são as características que permitem identificar que uma dessas fontes é confiável? ([Acessar o fórum](https://moodle.utfpr.edu.br/mod/forum/view.php?id=549655))

<!-- ## Wikipedon—Encontrar dados e informações de recursos do solo e da terra (20 min) -->
## Wikipedon—Identificar fontes de dados informações (20 min)
<!-- Descrição -->
<!-- Encontrar dados e informações dos recursos do solo e da terra do município que você e seus colegas de trabalho escolheram, usando a respectiva página de rascunho de teste para sua organização. Mais informações na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). -->
Identificar fontes de dados e informações dos recursos do solo e da terra do município que você e seus colegas de trabalho escolheram, usando a respectiva página de rascunho de teste para sua organização. Mais informações na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon).

##### Recursos adicionais

###### Palestra sobre acesso aberto aos dados da pesquisa em ciência do solo (SBCS) (1,5 h)

https://www.youtube.com/watch?v=xAW0JktjlOI&t=1758s
