# S04 SiBCS: estrutura e funcionamento

A quarta semana de atividades ficará marcada como sendo aquela em que você conhecerá a estrutura e funcionamento do Sistema Brasileiro de Classificação de Solos ([SiBCS](https://www.embrapa.br/en/solos/sibcs)). Para isso, você deve fazer a leitura de parte do Manual Técnico de Pedologia (IBGE, 2015, p. 185-203). Lá você vai conhecer um pouco da história do SiBCS e como ele chegou a ter a estrutura multi categórica, hierárquica e aberta que possui hoje. Você também vai conhecer os seis níveis categóricos do SiBCS e a nomenclatura utilizada em cada um deles, tendo a oportunidade de entender as razões por traz da formulação dos termos mais comumente utilizados. Ao final da semana, espera-se que você seja capaz de apontar as principais características sobre o funcionamento e estrutura do SiBCS—capacidade que será avaliada em nosso questionário semanal.

Durante esta semana você também deverá iniciar a redação do texto sobre os recursos do solo e da terra do município que você e seus colegas de trabalho escolheram. Para isso, vocês devem utilizar a página de rascunho de teste daquele município. Se você tiver dúvidas sobre como proceder, comece procurando por respostas na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). Você também pode participar de nosso encontro para resolução das dúvidas da semana (veja abaixo) ou deixar uma mensagem no [fórum de dúvidas e sugestões](https://moodle.utfpr.edu.br/mod/forum/view.php?id=573329).

## Encontro—Dúvidas da semana (Paluno, 50 min)

## Leitura—Manual Técnico de Pedologia (32 min)

* IBGE. __Capítulo 2.1 Taxonomia de solos__. In: IBGE. Manual Técnico de Pedologia. 3. ed. Rio de Janeiro, RJ: Instituto Brasileiro de Geografia e Estatística, 2015. p. 185-203. URL: <https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf>

## Questionário—SiBCS: estrutura e funcionamento (10 min)

## Fórum I—Fontes de dados e informações do solo (10 min)

Quais são as estratégias mais eficientes para encontrar fontes de dados e informações de recursos do solo e da terra de uma determinada região geográfica? Quais são as características que permitem identificar que uma dessas fontes é confiável? ([Acessar o fórum](https://moodle.utfpr.edu.br/mod/forum/view.php?id=549655))

## Wikipedon—Compilar dados e informações encontrados (40 min)

Compilar, na página de rascunho de teste do município escolhido, os dados e informações sobre os recursos do solo e da terra que você e seus colegas de trabalho encontraram. Mais informações na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon).
