# Semana 05

SiBCS: atributos diagnósticos

A última semana de atividades foi aquela em que você conheceu a estrutura e funcionamento do Sistema Brasileiro de Classificação de Solos ([SiBCS](https://www.embrapa.br/en/solos/sibcs)). Nesta semana, você conhecerá um elemento importante do SiBCS, os chamados _atributos diagnósticos_, e aprenderá como são utilizados na classificação de solos. Para isso, você deve fazer a leitura de parte do Manual Técnico de Pedologia (IBGE, 2015, p. 204-228). Você verá que há bastante [raciocínio lógico-matemático](https://pt.wikipedia.org/wiki/Racioc%C3%ADnio_l%C3%B3gico-matem%C3%A1tico) envolvido na definição dos atributos diagnósticos. Ao final da semana, espera-se que você seja capaz de __aplicar__ o SiBCS para identificação de atributos diagnósticos em perfis do solo. Essa capacidade será avaliada em nosso questionário semanal, que utilizará perfis de solo simulados.

Durante esta semana, você e seus colegas darão continuidade ao trabalho em grupo no projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). A tarefa desta semana consiste em contactar profissionais das ciências agrárias ou geociências com conhecimento prático do município escolhido por seu grupo. O principal objetivo do contato é convidar alguns especialistas locais para acompanhar a compilação de dados e informações sobre os recursos do solo e da terra daquele município. Se você tiver dúvidas sobre como proceder, comece procurando por respostas na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). Você também pode participar de nosso encontro para resolução das dúvidas da semana (veja abaixo) ou deixar uma mensagem no [fórum de dúvidas e sugestões](https://moodle.utfpr.edu.br/mod/forum/view.php?id=573329).

## Dúvidas da semana

Você tem dúvidas sobre as atividades da semana anterior? Quer saber mais sobre as atividades que terá que desenvolver na semana que está iniciando? Participe de nosso encontro semanal de resolução de dúvidas. Você também pode deixar uma mensagem no Fórum de Dúvidas e Sugestões.

* Informações gerais
  * Local: Moodle
  * Horário: 11:00–11:50
  * Duração prevista: 50 min
  * Gravação: não

## Leitura

Manual Técnico de Pedologia (43 min)
<!-- Descrição -->
* IBGE. __Seção 2.2.1.1 Atributos diagnósticos__. In: IBGE. Manual Técnico de Pedologia. 3. ed. Rio de Janeiro, RJ: Instituto Brasileiro de Geografia e Estatística, 2015. p. 204-227. URL: <https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf>
* IBGE. __Seção 2.2.1.2 Outros atributos__. In: IBGE. Manual Técnico de Pedologia. 3. ed. Rio de Janeiro, RJ: Instituto Brasileiro de Geografia e Estatística, 2015. p. 227-228. URL: <https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf>

## Questionário

SiBCS: atributos diagnósticos (10 min)

## Wikipedon

Contactar especialistas locais (15 min)
<!-- Descrição -->

Tarefa

__Contactar__ profissionais das ciências agrárias ou geociências com experiência no município escolhido por seu grupo, convidando-os para avaliar a acurácia (qualidade) e suficiência (quantidade) dos dados e informações sobre os recursos do solo e da terra compilados para aquele município.

Objetivo

__Validar__ a compilação de dados e informações sobre os recursos do solo e da terra, avaliando se o material compilado é acurado e suficiente para produzir conteúdo digital para o município escolhido por seu grupo.

Procedimentos

O contato deve ser realizado via correio eletrônico ou mídias sociais. Os conteúdos de texto e/ou áudio e/ou vídeo utilizados no contato devem ser salvos em [arquivo compactado](https://pt.wikipedia.org/wiki/Compactador_de_arquivos) (.7z .bdoc .cdoc .ddoc .gtar .gz .gzip .hqx .rar .sit .tar .tgz .zip), junto de arquivo de texto contendo os dados de identificação, endereço e contato dos especialistas. A comprovação da conclusão da atividade será mediante o envio do arquivo compactado. Mais informações na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon).

## Recursos adicionais

Aula sobre atributos diagnósticos (UFPR) (24 min)

https://youtu.be/aLhgbAB2FDY

Resumo sobre atributos diagnósticos (UFSM) (6 min)

https://youtu.be/9qLrWBGnvAY
