# Semana 10

SiBCS: Identificação das classes de solos

Você já conhece bastante sobre a estrutura do [SiBCS](https://www.embrapa.br/en/solos/sibcs). Agora está na hora de conhecer melhor como as classes de solo são identificadas. Como você já deve imaginar, isso depende da identificação prévia dos horizontes diagnósticos superficiais e subsuperficiais que estudamos nas semanas anteriores. Especificamente, você vai conhecer a chave de identificação das ordens, uma estrutura lógica similar àquelas com que você trabalhou em disciplinas das ciências biológicas. Além disso, vamos entrar numa nova fase do [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). Nela, você deixará de lado (temporariamente) o município em que está trabalhando para contribuir no desenvolvimento do artigo de outro grupo. Isso permitirá que você se familiarize com os recursos do solo e da terra de outra região. Também permitirá que você desenvolva sua habilidade de extrapolação, aplicando experiências prévias em um novo cenário geoespacial. O aprofundamento do estudo do SiBCS e do paradigma da relação solo-paisagem serão de grande ajuda nesse processo.

## Dúvidas da semana

Você tem dúvidas sobre as atividades da semana anterior? Quer saber mais sobre as atividades que terá que desenvolver na semana que está iniciando? Participe de nosso encontro semanal de resolução de dúvidas. Você também pode deixar uma mensagem no Fórum de Dúvidas e Sugestões.

* Informações gerais
  * Local: Moodle
  * Horário: 11:00–11:50
  * Duração prevista: 50 min
  * Gravação: não

## Leitura

Sistema Brasileiro de Classificação de Solos (12 min)

* Santos, H. G. et al. Capítulo 4 Classificação dos solos até o 4º nível categórico. In: Santos, H. G. et al. _Sistema Brasileiro de Classificação de Solos_. 5. ed. Brasília, DF: Empresa Brasileira de Pesquisa Agropecuária, 2018. p. 129-138. URL: <https://ainfo.cnptia.embrapa.br/digital/bitstream/item/199517/1/SiBCS-2018-ISBN-9788570358004.pdf>

## Leitura

Relação solo-paisagem (35 min)
<!-- A leitura do trabalho de revisão de Campos (2012) deve servir de subsídio para o desenvolvimento do fórum de discussão da semana. -->

* Campos, M. C. C. Relações solo-paisagem: conceitos, evolução e aplicações. _Ambiência_, v. 8, n. 3, p. 963-982, 2012. URL: <https://revistas.unicentro.br/index.php/ambiencia/article/view/1290>

## Fórum IV

Usando dados e informações de municípios vizinhos (20 min)
<!-- Esta é a segunda semana de discussão sobre o uso de dados e informações de municípios vizinhos. Na semana anterior, os alunos apontaram suas opiniões. Nesta segunda semana, após leitura de revisão bibliográfica sobre relações solo-paisagem, os alunos têm a oportunidade de rever suas posições iniciais. -->

Dados e informações detalhados e atualizados sobre os recursos do solo e da terra são necessários para tomar decisões importantes que afetam o ambiente e a economia. Contudo, muitos municípios não dispõe desses dados e informações. O modo mais apropriado de atender a essa demanda consiste em realizar [levantamentos de campo][cpt] e construir uma [base de dados espaciais][bd]. Isso geralmente requer grande volume de recursos—financeiros e humanos—e tempo. Assim, quando a demanda precisa ser atendida rapidamente—como é o caso do projeto Wikipedon—, costuma-se lançar mão de uma estratégia alternativa. Ela consiste em buscar dados e informações em áreas vizinhas que possuam condições ambientais similares. A [hipótese][hipotese] que fundamenta essa prática é baseada na relação solo-paisagem. Segundo a __relação solo-paisagem__, podemos [prever][prever] as características do solo num local de interesse em [função][funcao] das condições ambientais em que se encontra. Para isso, é necessário, primeiro, conhecer as características do solo em locais próximos que possuam condições ambientais similares. Quanto maior proximidade e similaridade das condições ambientais dos dois locais, maior será a credibilidade das previsões.

Tendo em vista os objetivos do Wikipedon e o prazo de entrega da atividade, discorra sobre como a relação solo-paisagem pode ser explorada para melhorar o artigo do município sob sua revisão nesta nova fase do Wikipedon.

[prever]: https://pt.wikipedia.org/wiki/Previs%C3%A3o_do_tempo
[bd]: https://pt.wikipedia.org/wiki/Banco_de_dados_espaciais
[cpt]: https://www.cpt.com.br/cursos-administracaorural/artigos/levantamento-de-recursos-naturais-como-e-por-que-fazer
[hipotese]: https://pt.wikipedia.org/wiki/Hip%C3%B3tese
[funcao]: https://pt.wikipedia.org/wiki/Fun%C3%A7%C3%A3o_(matem%C3%A1tica)
[confianca]: https://pt.wikipedia.org/wiki/Intervalo_de_confian%C3%A7a

## Wikipedon

Cooperar com pares na produção de conteúdo digital (30 min)
<!-- Revisão por pares -->

A [produção colaborativa][colabora] do conhecimento sobre os recursos do solo e da terra é uma das maneiras mais eficientes de garantir sua qualidade. Nessa nova fase do Wikipedon, você deixará de lado (temporariamente) o município em que está trabalhando para se dedicar ao município de outro grupo. Você tem a tarefa de analisar o conteúdo compilado para aquele município, realizando as alterações pertinentes para melhorar a qualidade do artigo. Dois aspectos devem ser analisados. Primeiro, a qualidade dos dados e informações compilados—caso você conheça outras fontes, deve incluir as mesmas no artigo. Segundo, a qualidade da apresentação do texto—isso inclui o respeito às regras de formatação e inclusão de [citações][citacao] e referências bibliográficas de modo apropriado, respeitando os direitos dos detentores de direito autoral. Ao final da semana, você deve apresentar um breve relato das contribuições feitas à melhoria do artigo.

[citacao]: https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Livro_de_estilo/Cite_as_fontes

## Recursos adicionais

Vídeos sobre relação solo-paisagem

https://www.youtube.com/playlist?list=PLJl3ZQuMf4kmAP_nfu5KCklYS0n0iM0MR
