# Semana 12

## Dúvidas da semana

Você tem dúvidas sobre as atividades da semana anterior? Quer saber mais sobre as atividades que terá que desenvolver na semana que está iniciando? Participe de nosso encontro semanal de resolução de dúvidas. Você também pode deixar uma mensagem no Fórum de Dúvidas e Sugestões.

* Informações gerais
  * Local: Moodle
  * Horário: 11:00–11:50
  * Duração prevista: 50 min
  * Gravação: não

## Wikipedon

A principal tarefa desta semana consiste em **identificar as relações espaciais existentes entre os recursos do solo e da terra de seu município de trabalho, reportando as mesmas na seção _Solos_**. Ao reportar essas relações solo-paisagem, forneca as informações necessárias para que leitores da Wikipédia sem familiaridade com ciência do solo compreendam a razão da ocorrência dos diferentes tipos de solos (e suas características) ao longo do território do município.

Enquanto você relata as relações solo-paisagem, fique atento às exigências do Wikipedon. As seis primeiras seções (apresentação, clima, geologia, relevo, hidrografia e vegetação) devem ter aproximadamente a mesma extensão. Enquanto isso, a sétima e mais importante seção deve ter a aproximadamente a mesma extensão do conjunto das seis primeiras. Por exemplo, **se cada uma das primeiras seis seções tiver dez linhas, a seção _Solos_ deve ter 10 x 6 = 60 linhas**.

O cumprimento da tarefa será aferido utilizando o registro do histórico de edições da página de seu município de trabalho.

* Duração estimada: 40 min

## Encontro

Relações entre Recursos do Solo e da Terra

A atividade prática da semana passada será repetida pelo fato de aquela não ter ficado gravada e disponível para os estudantes que não puderam participar.
