# Semana 01

Início das atividades

## Encontro

Planejamento de atividades (50 min)

<!-- Descrição -->

O encontro desta semana será nosso primeiro encontro desde março, quando as aulas presenciais foram suspensas por razão da pandemia do COVID‑19. Além de saber como você está, o objetivo é revisar o planejamento de atividades para o período não-presencial que vai até dezembro. Nós conversaremos sobre as leituras semanais que você terá que fazer de trechos do [Manual Técnico de Pedologia](https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf) e do [Sistema Brasileiro de Classificação de Solos](https://ainfo.cnptia.embrapa.br/digital/bitstream/item/199517/1/SiBCS-2018-ISBN-9788570358004.pdf). Também conversaremos sobre as avaliações individuais, que envolvem questionários e fóruns semanais. Por último, vamos tratar do trabalho em grupo, que consiste na participação em um projeto de extensão chamado [Wikipedon](https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Outreach_Dashboard/Universidade_Tecnol%C3%B3gica_Federal_do_Paran%C3%A1/Wikipedon_2020-02_(2020)), uma parceria da UTFPR com a Fundação Wikimedia.

Enquanto nosso encontro não chega, aproveite para se familiarizar com o Sistema Brasileiro de Classificação de Solos. Afinal de contas, ele será nosso companheiro de trabalho por quatro meses.

Bom trabalho e até breve!

__NOTA 1:__ Pode ocorrer sobrecarga da [Rede Nacional de Ensino e Pesquisa](https://pt.wikipedia.org/wiki/Rede_Nacional_de_Ensino_e_Pesquisa) (RNP) durante nosso encontro. Caso isso ocorra, utilizaremos uma sala alternativa do Google Classroom ([Pressione aqui para acessar](https://meet.google.com/lookup/c4saebrx42)).

__NOTA 2:__ Não se preocupe caso não consiga participar do encontro síncrono. Nosso encontro será gravado e ficará disponível aqui no Moodle para você assistir quando tiver condições.

__NOTA 3:__ O encontro será realizado em sala virtual do Moodle, utilizando o _plugin_ BibBlueButtonBN e a infraestrutura da [Rede Nacional de Ensino e Pesquisa](https://pt.wikipedia.org/wiki/Rede_Nacional_de_Ensino_e_Pesquisa) (RNP). A sala virtual será aberta às 10 h e 55 min. Para acessar, basta pressionar no título dessa atividade logo acima.

## Questionário

Gênese e morfologia do solo (10 min)

O questionário desta semana faz parte da primeira avaliação individual da disciplina AG63C Classificação de Solos. O objetivo é aferir seu conhecimento sobre gênese e morfologia do solo. São 10 questões a serem respondidas em até 10 minutos. Algumas dessas questões vão exigir menos de você do que outras. Assim, você tem, em média, um minuto para responder a cada questão. Caso seu desempenho não seja satisfatório, você dispõe de mais duas tentativas para melhorar sua nota. A cada tentativa, outras 10 novas questões, selecionadas aleatoriamente de um banco de questões, lhe serão apresentadas. A nota final será a média aritmética de todas as suas tentativas.

Antes de responder ao questionário, você pode refrescar a memória revendo suas anotações pessoais ou o material disponibilizado pelo professor da disciplina [AG62B Gênese e Morfologia do Solo](http://portal.utfpr.edu.br/cursos/coordenacoes/graduacao/santa-helena/sh-agronomia/matriz-e-docentes). Você também pode reler a seção _1.1 Caracterização Morfológica e Descrição dos Solos_ do [Manual Técnico de Pedologia](https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf) (IBGE, 2015, p. 39-151).

Bom trabalho e até breve!
