# Semana 06

SiBCS: horizontes diagnósticos

Nesta semana, você começará a conhecer mais um elemento importante do funcionamento do Sistema Brasileiro de Classificação de Solos ([SiBCS](https://www.embrapa.br/en/solos/sibcs)): os _horizontes diagnósticos_. Para isso, você deve fazer a leitura de parte do Manual Técnico de Pedologia (IBGE, 2015, p. 229-234) que trata dos _horizontes diagnósticos superficiais_. Você verá que, assim como para os atributos diagnósticos estudados na última semana de atividades, há bastante [raciocínio lógico-matemático](https://pt.wikipedia.org/wiki/Racioc%C3%ADnio_l%C3%B3gico-matem%C3%A1tico) envolvido na definição dos horizontes diagnósticos. Você também terá que fazer a leitura de um trecho do livro [Pedologia: Fundamentos](https://www.sbcs.org.br/loja/index.php?route=product/product&product_id=57) (RESENDE et al., 2012), editado pela Sociedade Brasileira de Ciência do Solo.
<!-- Ao final da semana, espera-se que você seja capaz de __explicar__ como as classes de solo do SiBCS são diferenciadas entre si. Essa capacidade será avaliada em nosso fórum. -->

Na semana passada, você e seus colegas contactaram profissionais das ciências agrárias ou geociências com conhecimento prático do município escolhido por seu grupo no projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). Em alguns casos, o retorno de um contato feito pode demorar. Em outros, pode ser preciso insistir no contato ou procurar por outros especialistas. Se o contato foi bem sucedido, então será preciso dar continuidade à conversa e explicar aos especialistas sobre o escopo do trabalho e como esperamos que auxiliem. Por isso, durante essa semana, você e seus colegas darão continuidade à atividade iniciada na semana passada. Lembre-se de que o objetivo é encontrar especialistas que possam acompanhar e contribuir para a compilação de dados e informações daquele município.  Se você tiver dúvidas sobre como proceder, comece procurando por respostas na página do projeto [Wikipedon](https://pt.wikiversity.org/wiki/Wikipedon). Você também pode participar de nosso encontro para resolução das dúvidas da semana (veja abaixo) ou deixar uma mensagem no [fórum de dúvidas](https://moodle.utfpr.edu.br/mod/forum/view.php?id=573329).

## Dúvidas da semana

Você tem dúvidas sobre as atividades da semana anterior? Quer saber mais sobre as atividades que terá que desenvolver na semana que está iniciando? Participe de nosso encontro semanal de resolução de dúvidas. Você também pode deixar uma mensagem no Fórum de Dúvidas e Sugestões.

* Informações gerais
  * Local: Moodle
  * Horário: 11:00–11:50
  * Duração prevista: 50 min
  * Gravação: não

## Leitura

Manual Técnico de Pedologia (8 min)

* IBGE. __Seção 2.2.1.3 Horizontes diagnósticos superficiais__. In: IBGE. Manual Técnico de Pedologia. 3. ed. Rio de Janeiro, RJ: Instituto Brasileiro de Geografia e Estatística, 2015. p. 229-234. URL: <https://biblioteca.ibge.gov.br/visualizacao/livros/liv95017.pdf>

## Leitura

Princípios da Classificação dos Solos (15 min)

* RESENDE, M. et al. __Princípios da classificação dos solos__. In: KER, J. C. et al. (Eds.) Pedologia: Fundamentos. Viçosa: Sociedade Brasileira de Ciência do Solo, 2012. p. 21–46. URL: <https://www.dropbox.com/s/1obglu7socskkla/ResendeEtAl2012_Princ%C3%ADpios_da_classifica%C3%A7%C3%A3o_dos_solos.pdf?dl=0>

## Wikipedon

(Re)Contactar especialistas locais (15 min)

## Encontro

Wikipedon: balanço de atividades e próximos passos (50 min)

<!-- ## Fórum II—Distinção de classes de solos (20 min) -->
<!-- Duração: de 3 semanas -->
<!-- O nível hierárquico mais alto do Sistema Brasileiro de Classificação de Solos ([SiBCS](https://www.embrapa.br/en/solos/sibcs)) possui treze classes chamadas de ordens. Cada ordem possui cinco níveis, dentro das quais são encontradas inúmeras categorias. Essas classes são diferenciadas utilizando _atributos_ e _horizontes diagnóstico_. -->

## Recursos adicionais

Aula sobre horizontes diagnósticos (UFPR) (17 min)

https://youtu.be/CQ3ruCSUaWE

Resumo sobre horizontes diagnósticos (InteraSolo) (3 min)

https://youtu.be/rrGkPzHeezM
